sudo: required
services:
 - docker
before_install:
 - docker build -f ./client/Dockerfile.dev -t new:latest ./client
script:
 - docker run -it new:latest npm test -- --coverage
after_success:
#docker build
 - docker build -t 26071995/new-client ./client
 - docker build -t 26071995/new-server ./server
 - docker build -t 26071995/new-ngnix ./nginx
 - docker build -t 26071995/new-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - echo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
# docker push to hub
 - docker push 26071995/new-client
 - docker push 26071995/new-server
 - docker push 26071995/new-ngnix
 - docker push 26071995/new-worker
#deploy project 
deploy:
 provider: elasticbeanstalk
 region: us-east-2
 app: MyDockerApp
 env: Mydockerappnew-env
 bucket_name: elasticbeanstalk-us-east-2-863659641122
 bucket_path: mynewDockerapp2
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY 
